--------------------------------------------------------
--  File created - Thursday-December-14-2023   
--------------------------------------------------------

--change the container to work in the PDB that was created by default with the oracle express inst
ALTER SESSION SET CONTAINER = XEPDB1;
--create a user/schema to have your own "persona space" in the XEPDB1 pluggable databse
CREATE USER FINAL_2232086 IDENTIFIED BY 123; 
--grant the permission to NEW DATABASE to connect and creat objects(tables.etc)
GRANT CONNECT, RESOURCE TO FINAL_2232086;
--give the persmision to  NEW DATABASE  to also write data in the tables
GRANT UNLIMITED TABLESPACE TO FINAL_2232086;

ALTER SESSION SET CURRENT_SCHEMA = FINAL_2232086;

--------------------------------------------------------
--  DDL for Sequence SEQUENCE_INVOICE
--------------------------------------------------------

   CREATE SEQUENCE  "FINAL_2232086"."SEQUENCE_INVOICE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 650 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Table CUSTOMERS
--------------------------------------------------------

  CREATE TABLE "FINAL_2232086"."CUSTOMERS" 
   (	"CUSTOMER_ID" VARCHAR2(32 BYTE) DEFAULT SYS_GUID(), 
	"FIRSTNAME" VARCHAR2(20 BYTE), 
	"LASTNAME" VARCHAR2(20 BYTE), 
	"ADDRESS" VARCHAR2(20 BYTE), 
	"CITY" VARCHAR2(20 BYTE), 
	"POSTAL_CODE" VARCHAR2(20 BYTE), 
	"CREATE_DATE_TIME" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	"MODIFY_DATE_TIME" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "FINAL_2232086"."CUSTOMERS"."CUSTOMER_ID" IS ' 2023-12-14  NATALIA HERRERA( 2232086)
Created the table
';
--------------------------------------------------------
--  DDL for Table PRODUCTS
--------------------------------------------------------

  CREATE TABLE "FINAL_2232086"."PRODUCTS" 
   (	"PRODUCT_ID" VARCHAR2(32 BYTE) DEFAULT SYS_GUID(), 
	"PRODUCT_NAME" VARCHAR2(20 BYTE), 
	"PRICE" NUMBER(5,2), 
	"PRODUCT_DESCRIPTION" VARCHAR2(100 CHAR), 
	"CREATE_DATE_TIME" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	"MODIFY_DATE_TIME" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "FINAL_2232086"."PRODUCTS"."PRODUCT_ID" IS ' 2023-12-14  NATALIA HERRERA( 2232086)
Created the table
';
--------------------------------------------------------
--  DDL for Table SALES
--------------------------------------------------------

  CREATE TABLE "FINAL_2232086"."SALES" 
   (	"SALES_ID" VARCHAR2(32 BYTE) DEFAULT SYS_GUID(), 
	"CUSTOMER_ID" VARCHAR2(32 BYTE), 
	"PRODUCT_ID" VARCHAR2(32 BYTE), 
	"QUANTITY" NUMBER, 
	"TOTAL_PRICE" NUMBER(7,2), 
	"INVOICE_NUMBER" VARCHAR2(20 BYTE), 
	"CREATE_DATE_TIME" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	"MODIFY_DATE_TIME" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "FINAL_2232086"."SALES"."SALES_ID" IS ' 2023-12-14  NATALIA HERRERA( 2232086)
Created the table';
--------------------------------------------------------
--  DDL for Table USER_WEBSITE
--------------------------------------------------------

  CREATE TABLE "FINAL_2232086"."USER_WEBSITE" 
   (	"USER_ID" VARCHAR2(32 BYTE) DEFAULT SYS_GUID(), 
	"EMAIL" VARCHAR2(20 BYTE), 
	"PASSWORD" NUMBER, 
	"CUSTOMER_ID" VARCHAR2(32 BYTE), 
	"CREATE_DATE_TIME" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	"MODIFY_DATE_TIME" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "FINAL_2232086"."USER_WEBSITE"."USER_ID" IS ' 2023-12-14  NATALIA HERRERA( 2232086)
Created the table
';
REM INSERTING into FINAL_2232086.CUSTOMERS
SET DEFINE OFF;
Insert into FINAL_2232086.CUSTOMERS (CUSTOMER_ID,FIRSTNAME,LASTNAME,ADDRESS,CITY,POSTAL_CODE,CREATE_DATE_TIME,MODIFY_DATE_TIME) values ('5DA47901ECD04EBFA8F41231970067D4','NATALIA','HERRERA','1236 PLAMONDON','MONTREAL','H2K3B7',to_timestamp('23-12-14 17:54:26.401000000','RR-MM-DD HH24:MI:SSXFF'),to_timestamp('23-12-14 17:54:26.401000000','RR-MM-DD HH24:MI:SSXFF'));
Insert into FINAL_2232086.CUSTOMERS (CUSTOMER_ID,FIRSTNAME,LASTNAME,ADDRESS,CITY,POSTAL_CODE,CREATE_DATE_TIME,MODIFY_DATE_TIME) values ('BB5D54C9C5F649298DFC0076E6C48735','GLADYS','ESPINOSA','3664 SNOWDOWN','MONTREAL','h2k3b7',to_timestamp('23-12-14 17:54:26.408000000','RR-MM-DD HH24:MI:SSXFF'),to_timestamp('23-12-14 17:54:26.408000000','RR-MM-DD HH24:MI:SSXFF'));
Insert into FINAL_2232086.CUSTOMERS (CUSTOMER_ID,FIRSTNAME,LASTNAME,ADDRESS,CITY,POSTAL_CODE,CREATE_DATE_TIME,MODIFY_DATE_TIME) values ('ADA839F12C5A417D9478CA924B73D67F','ANA','OSPINA','3651 LAVAL','LAVA','h2k 3b2',to_timestamp('23-12-14 17:54:26.409000000','RR-MM-DD HH24:MI:SSXFF'),to_timestamp('23-12-14 17:54:26.409000000','RR-MM-DD HH24:MI:SSXFF'));
REM INSERTING into FINAL_2232086.PRODUCTS
SET DEFINE OFF;
Insert into FINAL_2232086.PRODUCTS (PRODUCT_ID,PRODUCT_NAME,PRICE,PRODUCT_DESCRIPTION,CREATE_DATE_TIME,MODIFY_DATE_TIME) values ('DC5507B1755A431F830820A2950BB7EB','BOOK',15,'BLABALBA',to_timestamp('23-12-14 17:57:43.786000000','RR-MM-DD HH24:MI:SSXFF'),to_timestamp('23-12-14 17:57:43.786000000','RR-MM-DD HH24:MI:SSXFF'));
Insert into FINAL_2232086.PRODUCTS (PRODUCT_ID,PRODUCT_NAME,PRICE,PRODUCT_DESCRIPTION,CREATE_DATE_TIME,MODIFY_DATE_TIME) values ('DCCC405E9AAC45AE9158215B1EBC6FC2','PENCIL',5,'AFSGGY',to_timestamp('23-12-14 17:57:43.792000000','RR-MM-DD HH24:MI:SSXFF'),to_timestamp('23-12-14 17:57:43.792000000','RR-MM-DD HH24:MI:SSXFF'));
Insert into FINAL_2232086.PRODUCTS (PRODUCT_ID,PRODUCT_NAME,PRICE,PRODUCT_DESCRIPTION,CREATE_DATE_TIME,MODIFY_DATE_TIME) values ('8E084E10B0644D9C918B7C7B815A332C','NOTEBOOK',3,'EREWRTRY',to_timestamp('23-12-14 17:57:43.793000000','RR-MM-DD HH24:MI:SSXFF'),to_timestamp('23-12-14 17:57:43.793000000','RR-MM-DD HH24:MI:SSXFF'));
REM INSERTING into FINAL_2232086.SALES
SET DEFINE OFF;
Insert into FINAL_2232086.SALES (SALES_ID,CUSTOMER_ID,PRODUCT_ID,QUANTITY,TOTAL_PRICE,INVOICE_NUMBER,CREATE_DATE_TIME,MODIFY_DATE_TIME) values ('600FFADA47BB4052AD8F123C5AA29483','5DA47901ECD04EBFA8F41231970067D4','DC5507B1755A431F830820A2950BB7EB',5,60,'INVOICE_601',to_timestamp('23-12-14 17:58:50.532000000','RR-MM-DD HH24:MI:SSXFF'),to_timestamp('23-12-14 17:58:50.532000000','RR-MM-DD HH24:MI:SSXFF'));
Insert into FINAL_2232086.SALES (SALES_ID,CUSTOMER_ID,PRODUCT_ID,QUANTITY,TOTAL_PRICE,INVOICE_NUMBER,CREATE_DATE_TIME,MODIFY_DATE_TIME) values ('590999E2900E4B2D9C6263528459A158','5DA47901ECD04EBFA8F41231970067D4','DC5507B1755A431F830820A2950BB7EB',3,5,'INVOICE_602',to_timestamp('23-12-14 17:59:15.359000000','RR-MM-DD HH24:MI:SSXFF'),to_timestamp('23-12-14 17:59:15.359000000','RR-MM-DD HH24:MI:SSXFF'));
REM INSERTING into FINAL_2232086.USER_WEBSITE
SET DEFINE OFF;
Insert into FINAL_2232086.USER_WEBSITE (USER_ID,EMAIL,PASSWORD,CUSTOMER_ID,CREATE_DATE_TIME,MODIFY_DATE_TIME) values ('EB1333730BFB44C298EE47BF835B91C4','EXAMPLE@EXAMPLE.COM',123,'5DA47901ECD04EBFA8F41231970067D4',to_timestamp('23-12-14 17:54:59.114000000','RR-MM-DD HH24:MI:SSXFF'),to_timestamp('23-12-14 17:54:59.114000000','RR-MM-DD HH24:MI:SSXFF'));
Insert into FINAL_2232086.USER_WEBSITE (USER_ID,EMAIL,PASSWORD,CUSTOMER_ID,CREATE_DATE_TIME,MODIFY_DATE_TIME) values ('29EB348803C24A95BE4DB3B5ECA84728','EXAMPLE2@EXAMPLE.COM',2134,'BB5D54C9C5F649298DFC0076E6C48735',to_timestamp('23-12-14 17:55:20.364000000','RR-MM-DD HH24:MI:SSXFF'),to_timestamp('23-12-14 17:55:20.364000000','RR-MM-DD HH24:MI:SSXFF'));
Insert into FINAL_2232086.USER_WEBSITE (USER_ID,EMAIL,PASSWORD,CUSTOMER_ID,CREATE_DATE_TIME,MODIFY_DATE_TIME) values ('F5944E32F99C45CAAEC98927C399B7C7','EXAMPLE@EXAMPLE3.COM',2586,'ADA839F12C5A417D9478CA924B73D67F',to_timestamp('23-12-14 17:55:40.965000000','RR-MM-DD HH24:MI:SSXFF'),to_timestamp('23-12-14 17:55:40.965000000','RR-MM-DD HH24:MI:SSXFF'));
--------------------------------------------------------
--  DDL for Index PRODUCTS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FINAL_2232086"."PRODUCTS_PK" ON "FINAL_2232086"."PRODUCTS" ("PRODUCT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index USER_WEBSITE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FINAL_2232086"."USER_WEBSITE_PK" ON "FINAL_2232086"."USER_WEBSITE" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CUSTOMERS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FINAL_2232086"."CUSTOMERS_PK" ON "FINAL_2232086"."CUSTOMERS" ("CUSTOMER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SALES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FINAL_2232086"."SALES_PK" ON "FINAL_2232086"."SALES" ("SALES_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index USER_WEBSITE_EMAIL_UK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FINAL_2232086"."USER_WEBSITE_EMAIL_UK" ON "FINAL_2232086"."USER_WEBSITE" ("EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger TG_ADDRESS_VALIDATION
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "FINAL_2232086"."TG_ADDRESS_VALIDATION" 
BEFORE INSERT ON CUSTOMERS 
FOR EACH ROW 
BEGIN
   /* 2023-12-14  NATALIA HERRERA( 2232086)
  CREATE TRIGGER WITH REGEX VALIDATION
  Trigger created to perform regex-based validation of the postal code of the customer to be like quebec postal code*/
  IF NOT regexp_like(:new.POSTAL_CODE,'^[A-Za-z0-9]{3} ?[A-Za-z0-9]{3}$', 'i') THEN
        RAISE_APPLICATION_ERROR(-20001, 'Invalid postal code format. It should be like H2K3B7 or h2k 3b7.');
    END IF;
END;
/
ALTER TRIGGER "FINAL_2232086"."TG_ADDRESS_VALIDATION" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TG_CUSTOMERS_MODIFY
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "FINAL_2232086"."TG_CUSTOMERS_MODIFY" 
BEFORE UPDATE ON CUSTOMERS 
FOR EACH ROW 
BEGIN
      /* 2023-12-14 NATALIA HERRERA( 2232086)
  CREATE TRIGGER TO UPDATE DATE */
    -- Use the current date/time (now) and put it into the modif field   
  :NEW.MODIFY_DATE_TIME := CURRENT_TIMESTAMP;
END;
/
ALTER TRIGGER "FINAL_2232086"."TG_CUSTOMERS_MODIFY" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TG_PRODUCTS_MODIFY
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "FINAL_2232086"."TG_PRODUCTS_MODIFY" 
BEFORE UPDATE ON PRODUCTS 
FOR EACH ROW 
BEGIN
      /* 2023-12-14 NATALIA HERRERA( 2232086)
  CREATE TRIGGER TO UPDATE DATE */
    -- Use the current date/time (now) and put it into the modif field   
  :NEW.MODIFY_DATE_TIME := CURRENT_TIMESTAMP;
END;
/
ALTER TRIGGER "FINAL_2232086"."TG_PRODUCTS_MODIFY" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TG_SALES_MODIFY
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "FINAL_2232086"."TG_SALES_MODIFY" 
BEFORE UPDATE ON SALES 
FOR EACH ROW 
BEGIN
      /* 2023-12-14 NATALIA HERRERA( 2232086)
  CREATE TRIGGER TO UPDATE DATE */
    -- Use the current date/time (now) and put it into the modif field   
  :NEW.MODIFY_DATE_TIME := CURRENT_TIMESTAMP;
END;
/
ALTER TRIGGER "FINAL_2232086"."TG_SALES_MODIFY" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TG_USER_MODIFY
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "FINAL_2232086"."TG_USER_MODIFY" 
BEFORE UPDATE ON USER_WEBSITE 
FOR EACH ROW 
BEGIN
      /* 2023-12-14 NATALIA HERRERA( 2232086)
  CREATE TRIGGER TO UPDATE DATE */
    -- Use the current date/time (now) and put it into the modif field   
  :NEW.MODIFY_DATE_TIME := CURRENT_TIMESTAMP;
END;
/
ALTER TRIGGER "FINAL_2232086"."TG_USER_MODIFY" ENABLE;
--------------------------------------------------------
--  DDL for Procedure CUSTOMER_DELETE
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "FINAL_2232086"."CUSTOMER_DELETE" 
(PARAM_CUSTOMER_ID	VARCHAR2)
AS 
BEGIN
/*2023-12-14  NATALIA HERRERA( 2232086)
   DELETE DATA FOR CUSTOMER TABLE*/
   DELETE CUSTOMERS
        WHERE CUSTOMER_ID = PARAM_CUSTOMER_ID;
    -- Save the fields in the table
  COMMIT;
  
END CUSTOMER_DELETE;

/
--------------------------------------------------------
--  DDL for Procedure CUSTOMER_INSERT
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "FINAL_2232086"."CUSTOMER_INSERT" (
 PARAM_FIRSTNAME	VARCHAR2,
 PARAM_LASTNAME	VARCHAR2,
 PARAM_ADDRESS	VARCHAR2,
 PARAM_CITY	VARCHAR2,
 PARAM_POSTAL_CODE	VARCHAR2)
AS 
BEGIN
/*2023-12-14  NATALIA HERRERA( 2232086)
   INSERT DATA FOR CUSTOMER*/
   INSERT INTO CUSTOMERS(
        FIRSTNAME,
        LASTNAME,
        ADDRESS,
        CITY,
        POSTAL_CODE)
    VALUES (   PARAM_FIRSTNAME,
        PARAM_LASTNAME,
        PARAM_ADDRESS,
        PARAM_CITY,
        PARAM_POSTAL_CODE);
  COMMIT;
  
END CUSTOMER_INSERT;

/
--------------------------------------------------------
--  DDL for Procedure CUSTOMER_UPDATE
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "FINAL_2232086"."CUSTOMER_UPDATE" (
PARAM_CUSTOMER_ID	VARCHAR2,
 PARAM_FIRSTNAME	VARCHAR2,
 PARAM_LASTNAME	VARCHAR2,
 PARAM_ADDRESS	VARCHAR2,
 PARAM_CITY	VARCHAR2,
 PARAM_POSTAL_CODE	VARCHAR2)
AS 
BEGIN
/*2023-12-14  NATALIA HERRERA( 2232086)
   UPDATE DATA FOR CUSTOMER*/
   UPDATE CUSTOMERS
   SET 
        FIRSTNAME = PARAM_FIRSTNAME,
        LASTNAME=PARAM_LASTNAME,
        ADDRESS=PARAM_ADDRESS,
        CITY=PARAM_CITY,
        POSTAL_CODE=PARAM_POSTAL_CODE
        WHERE CUSTOMER_ID = PARAM_CUSTOMER_ID;
    -- Save the fields in the table
  COMMIT;
  
END CUSTOMER_UPDATE;

/
--------------------------------------------------------
--  DDL for Procedure PRODUCT_DELETE
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "FINAL_2232086"."PRODUCT_DELETE" (
PARAM_PRODUCT_ID	VARCHAR2)
AS 
BEGIN
/*2023-12-14  NATALIA HERRERA( 2232086)
   DELETE DATA FOR PRODUCTS*/
   DELETE PRODUCTS
   
            WHERE PRODUCT_ID = PARAM_PRODUCT_ID;

  COMMIT; -- Save the fields in the table
  
END PRODUCT_DELETE;

/
--------------------------------------------------------
--  DDL for Procedure PRODUCT_INSERT
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "FINAL_2232086"."PRODUCT_INSERT" (
PARAM_PRODUCT_NAME	VARCHAR2,
PARAM_PRICE	NUMBER,
PARAM_PRODUCT_DESCRIPTION	VARCHAR2)
AS 
BEGIN
/*2023-12-14  NATALIA HERRERA( 2232086)
   INSERT DATA FOR PRODUCTS*/
   INSERT INTO PRODUCTS
            (PRODUCT_NAME,
            PRICE,
            PRODUCT_DESCRIPTION)
    VALUES (  PARAM_PRODUCT_NAME,
            PARAM_PRICE	,
            PARAM_PRODUCT_DESCRIPTION);
  COMMIT;
  
END PRODUCT_INSERT;

/
--------------------------------------------------------
--  DDL for Procedure PRODUCT_UPDATE
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "FINAL_2232086"."PRODUCT_UPDATE" (
PARAM_PRODUCT_ID	VARCHAR2,
PARAM_PRODUCT_NAME	VARCHAR2,
PARAM_PRICE	NUMBER,
PARAM_PRODUCT_DESCRIPTION	VARCHAR2)
AS 
BEGIN
/*2023-12-14  NATALIA HERRERA( 2232086)
   UPDATE DATA FOR PRODUCTS*/
   UPDATE PRODUCTS
    SET      PRODUCT_NAME =PARAM_PRODUCT_NAME,
            PRICE=PARAM_PRICE,
            PRODUCT_DESCRIPTION=PARAM_PRODUCT_DESCRIPTION
            WHERE PRODUCT_ID = PARAM_PRODUCT_ID;

  COMMIT; -- Save the fields in the table
  
END PRODUCT_UPDATE;

/
--------------------------------------------------------
--  DDL for Procedure SALES_DELETE
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "FINAL_2232086"."SALES_DELETE" 
(PARAM_SALES_ID	VARCHAR2
)AS 

BEGIN

/*2023-12-14  NATALIA HERRERA( 2232086)
   DELETE DATA FOR SALES*/

   DELETE SALES

    WHERE SALES_ID = PARAM_SALES_ID;
    COMMIT;
END SALES_DELETE;

/
--------------------------------------------------------
--  DDL for Procedure SALES_INSERT
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "FINAL_2232086"."SALES_INSERT" 
(
PARAM_CUSTOMER_ID	VARCHAR2,
PARAM_PRODUCT_ID	VARCHAR2,
PARAM_QUANTITY	NUMBER,
PARAM_TOTAL_PRICE NUMBER,
PARAM_INVOICE_NUMBER	VARCHAR2
)AS 
V_INVOICE VARCHAR2(11):= 'INVOICE_';
V_SEQ VARCHAR2(3);

BEGIN

/*2023-12-14  NATALIA HERRERA( 2232086)
   UPDATE SALES WITH SEQ INVOICE */
   
   /*GENERATE TE SEQUENCE TO DO THE NEXT NUMBER*/
    SELECT
       SEQUENCE_INVOICE.NEXTVAL
    INTO v_SEQ
    FROM
        dual;
   
  INSERT INTO SALES (CUSTOMER_ID,
        PRODUCT_ID,
        QUANTITY,
        TOTAL_PRICE,
        INVOICE_NUMBER)
    VALUES (   PARAM_CUSTOMER_ID,
        PARAM_PRODUCT_ID,
        PARAM_QUANTITY,
        PARAM_TOTAL_PRICE,
        V_INVOICE||V_SEQ);
   

    COMMIT;
END SALES_INSERT;

/
--------------------------------------------------------
--  DDL for Procedure SALES_UPDATE
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "FINAL_2232086"."SALES_UPDATE" 
(PARAM_SALES_ID	VARCHAR2,
PARAM_CUSTOMER_ID	VARCHAR2,
PARAM_PRODUCT_ID	VARCHAR2,
PARAM_QUANTITY	NUMBER,
PARAM_INVOICE_NUMBER	VARCHAR2
)AS 
V_INVOICE VARCHAR2(11):= 'INVOICE_';
V_SEQ VARCHAR2(3);

BEGIN

/*2023-12-14  NATALIA HERRERA( 2232086)
   UPDATE SALES WITH SEQ INVOICE */
   
   /*GENERATE TE SEQUENCE TO DO THE NEXT NUMBER*/
    SELECT
       SEQUENCE_INVOICE.NEXTVAL
    INTO v_SEQ
    FROM
        dual;
   
  UPDATE SALES
    SET CUSTOMER_ID=PARAM_CUSTOMER_ID,
    PRODUCT_ID=PARAM_PRODUCT_ID,
    QUANTITY=PARAM_QUANTITY,
    INVOICE_NUMBER= V_INVOICE||V_SEQ
     WHERE SALES_ID = PARAM_SALES_ID;
   

    COMMIT;
END SALES_UPDATE;

/
--------------------------------------------------------
--  DDL for Procedure USER_WEBSITE_DELETE
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "FINAL_2232086"."USER_WEBSITE_DELETE" 
(PARAM_USER_ID VARCHAR2
)
AS 
BEGIN
/*2023-12-14  NATALIA HERRERA( 2232086)
   DELETE DATA FOR USER WEBSITE */
   
   DELETE USER_WEBSITE
    
             WHERE USER_ID = PARAM_USER_ID;
  
  COMMIT;
  
END USER_WEBSITE_DELETE;

/
--------------------------------------------------------
--  DDL for Procedure USER_WEBSITE_INSERT
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "FINAL_2232086"."USER_WEBSITE_INSERT" 
(
PARAM_EMAIL	VARCHAR2,
PARAM_PASSWORD	VARCHAR2,
PARAM_CUSTOMER_ID	VARCHAR2
)
AS 
BEGIN
/*2023-12-14  NATALIA HERRERA( 2232086)
   INSERT DATA FOR USER WEBSITE WITH PASSWORD WITH HASH*/
   
   INSERT INTO USER_WEBSITE
            (EMAIL,
            PASSWORD,
            CUSTOMER_ID)
    VALUES ( PARAM_EMAIL,
            ORA_HASH(PARAM_PASSWORD),
            PARAM_CUSTOMER_ID);
  COMMIT;
  
END USER_WEBSITE_INSERT;

/
--------------------------------------------------------
--  DDL for Procedure USER_WEBSITE_UPDATE
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "FINAL_2232086"."USER_WEBSITE_UPDATE" 
(PARAM_USER_ID VARCHAR2,
PARAM_EMAIL	VARCHAR2,
PARAM_PASSWORD	VARCHAR2,
PARAM_CUSTOMER_ID	VARCHAR2
)
AS 
BEGIN
/*2023-12-14  NATALIA HERRERA( 2232086)
   UPDATE DATA FOR USER WEBSITE WITH PASSWORD WITH HASH*/
   
   UPDATE USER_WEBSITE
     SET    EMAIL=PARAM_EMAIL,
            PASSWORD=ORA_HASH(PARAM_PASSWORD),
            CUSTOMER_ID=PARAM_CUSTOMER_ID
             WHERE USER_ID = PARAM_USER_ID;
  
  COMMIT;
  
END USER_WEBSITE_UPDATE;

/
--------------------------------------------------------
--  DDL for Function FC_CONNECT
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE FUNCTION "FINAL_2232086"."FC_CONNECT" 
(PARAM_EMAIL IN VARCHAR2 ,
PARAM_PASSWORD IN VARCHAR2 
) RETURN VARCHAR2 AS 
  FOUND_USER_ID VARCHAR(32) := NULL;
BEGIN
/*2023-12-14  NATALIA HERRERA( 2232086)
   FUNCTION TO CONNECT THE USER, SEE IF THE EMAIL AND PASSWORD WITH HASH IS THE SAME AS THE DATABASE IN ORDER TO LET LOGGIN THE CUSTOMER*/
     SELECT EMAIL INTO FOUND_USER_ID
    FROM USER_WEBSITE
    --CHECK IF THE EMAIL EXIST
    WHERE EMAIL = PARAM_EMAIL
    --CHECK PASSWORD
    AND PASSWORD = ORA_HASH(PARAM_PASSWORD);
    --LOGIN RETURN
    RETURN '1';
    -- DOESNT MATCH
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RETURN '0';
END FC_CONNECT;

/
--------------------------------------------------------
--  DDL for Function FC_SALES_CUSTOMER
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE FUNCTION "FINAL_2232086"."FC_SALES_CUSTOMER" RETURN VARCHAR2  PIPELINED AS 
BEGIN

/*2023-12-14  NATALIA HERRERA( 2232086)
   FUNCTION TO DISPLAY PURCHASES IN BDMS*/
   
   SELECT
    s.product_id,
    p.product_name,
    s.quantity,
    ORA_HASH(s.quantity),
    ORA_HASH('NATALIA'),
    p.product_price,
    s.quantity * p.product_price AS total,
    fc_get_total_price_if(p.product_price, s.quantity)
FROM
         sales s
    INNER JOIN product p ON s.product_id = p.product_id
    
  FOR NH IN (
        SELECT
            C.LASTNAME,
            C.FIRSTNAME,
            P.PRODUCT_ID,
            P.PRODUCT_NAME,
            P.PRODUCT_DESCRIPTION,
            P.PRICE,
            S.QUANTITY
        FROM
            CUSTOMERS C
            JOIN PRODUCTS P ON P.PRODUCT_ID = S.PRODUCT_ID
            JOIN SALES S ON S.CUSTOMER_ID = C.CUSTOMER_ID
        ORDER BY P.PRODUCT_ID
    ) LOOP
        PIPE ROW (sales_customer_typ(
            NH.LASTNAME,
            NH.FIRSTNAME,
            NH.PRODUCT_ID,
            NH.PRODUCT_NAME,
            NH.PRODUCT_DESCRIPTION,
            NH.PRICE,
            NH.QUANTITY,
            FC_SALES_TOTAL_PRICE(NH.PRICE, NH.QUANTITY)
        ));
            -- Output  details who meet the condition and pipe them into the output table type
         DBMS_OUTPUT.PUT_LINE('LAST NAME: '|| NH.LASTNAME || 'FIRST NAME: ' 
                        || NH.FIRSTNAME || 'PRODUCT ID: ' ||NH.PRODUCT_ID || 'PRODUCT NAME: ' ||NH.PRODUCT_NAME || 'PRODUCTDESCRIPTION: ' ||NH.PRODUCT_DESCRIPTION
                        || 'PRICE: ' ||NH.PRICE|| 'QUANTITY: ' ||NH.QUANTITY|| 'TOTAL: ' ||NH.FC_SALES_TOTAL_PRICE(PARAM_PRICE * PARAM_QUANTITY)|| 
                        'CUMULATIVE: ' ||NH.SUM(FC_SALES_TOTAL_PRICE(PARAM_PRICE * PARAM_QUANTITY));
        
    END LOOP;
    -- End of loop, return from the function
END FC_SALES_CUSTOMER;

/
--------------------------------------------------------
--  DDL for Function FC_SALES_TOTAL_PRICE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE FUNCTION "FINAL_2232086"."FC_SALES_TOTAL_PRICE" 
(
  PARAM_PRICE IN NUMBER 
, PARAM_QUANTITY IN NUMBER 
) RETURN NUMBER AS 
TOTAL_PRICE NUMBER;
BEGIN
 /* 2023-12-14 NATALIA HERRERA( 2232086)
  CREATE FUNCTION 
  
  SIMPLE CALCULATION FOR THE PRICE X QUANTITY SOLD*/

TOTAL_PRICE :=(PARAM_PRICE * PARAM_QUANTITY);

  RETURN TOTAL_PRICE;
END FC_SALES_TOTAL_PRICE;

/
--------------------------------------------------------
--  DDL for Function FC_SEARCH_CUSTOMERS
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE FUNCTION "FINAL_2232086"."FC_SEARCH_CUSTOMERS" 
(PARAM_LASTNAME VARCHAR2)
RETURN VARCHAR2 AS 
CUSTOMER_LASTNAME VARCHAR(20) := '';
BEGIN

/*2023-12-14  NATALIA HERRERA( 2232086)
   FUNCTION TO SEARCH THE CUSTOMER LASTANAME , JUST ADDING PART OF THE NAME AND DISPLAY EVERYTHIGN THAT CONTENT THAT*/
   
    FOR NH IN (SELECT LASTNAME 
                FROM CUSTOMERS 
    WHERE REGEXP_LIKE(LASTNAME, PARAM_LASTNAME, 'i')) --REGEX TO SEARCH THE CHARACTERS
    LOOP --LOOP TO DISPLAY ALL OF THEM
      CUSTOMER_LASTNAME := CUSTOMER_LASTNAME || NH.LASTNAME || '; '; 
   END LOOP;
   
 RETURN CUSTOMER_LASTNAME;
END FC_SEARCH_CUSTOMERS;

/
--------------------------------------------------------
--  Constraints for Table SALES
--------------------------------------------------------

  ALTER TABLE "FINAL_2232086"."SALES" MODIFY ("SALES_ID" NOT NULL ENABLE);
  ALTER TABLE "FINAL_2232086"."SALES" MODIFY ("CUSTOMER_ID" NOT NULL ENABLE);
  ALTER TABLE "FINAL_2232086"."SALES" MODIFY ("PRODUCT_ID" NOT NULL ENABLE);
  ALTER TABLE "FINAL_2232086"."SALES" MODIFY ("QUANTITY" NOT NULL ENABLE);
  ALTER TABLE "FINAL_2232086"."SALES" MODIFY ("TOTAL_PRICE" NOT NULL ENABLE);
  ALTER TABLE "FINAL_2232086"."SALES" MODIFY ("INVOICE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "FINAL_2232086"."SALES" MODIFY ("CREATE_DATE_TIME" NOT NULL ENABLE);
  ALTER TABLE "FINAL_2232086"."SALES" MODIFY ("MODIFY_DATE_TIME" NOT NULL ENABLE);
  ALTER TABLE "FINAL_2232086"."SALES" ADD CONSTRAINT "SALES_PK" PRIMARY KEY ("SALES_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CUSTOMERS
--------------------------------------------------------

  ALTER TABLE "FINAL_2232086"."CUSTOMERS" MODIFY ("CUSTOMER_ID" NOT NULL ENABLE);
  ALTER TABLE "FINAL_2232086"."CUSTOMERS" MODIFY ("FIRSTNAME" NOT NULL ENABLE);
  ALTER TABLE "FINAL_2232086"."CUSTOMERS" MODIFY ("LASTNAME" NOT NULL ENABLE);
  ALTER TABLE "FINAL_2232086"."CUSTOMERS" MODIFY ("ADDRESS" NOT NULL ENABLE);
  ALTER TABLE "FINAL_2232086"."CUSTOMERS" MODIFY ("CITY" NOT NULL ENABLE);
  ALTER TABLE "FINAL_2232086"."CUSTOMERS" MODIFY ("POSTAL_CODE" NOT NULL ENABLE);
  ALTER TABLE "FINAL_2232086"."CUSTOMERS" MODIFY ("CREATE_DATE_TIME" NOT NULL ENABLE);
  ALTER TABLE "FINAL_2232086"."CUSTOMERS" MODIFY ("MODIFY_DATE_TIME" NOT NULL ENABLE);
  ALTER TABLE "FINAL_2232086"."CUSTOMERS" ADD CONSTRAINT "CUSTOMERS_PK" PRIMARY KEY ("CUSTOMER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PRODUCTS
--------------------------------------------------------

  ALTER TABLE "FINAL_2232086"."PRODUCTS" MODIFY ("PRODUCT_ID" NOT NULL ENABLE);
  ALTER TABLE "FINAL_2232086"."PRODUCTS" MODIFY ("PRODUCT_DESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "FINAL_2232086"."PRODUCTS" ADD CONSTRAINT "PRODUCTS_PK" PRIMARY KEY ("PRODUCT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "FINAL_2232086"."PRODUCTS" ADD CONSTRAINT "PRODUCTS_PRICE_CHK" CHECK (PRICE >= 0 AND
PRICE <= 500) ENABLE;
  ALTER TABLE "FINAL_2232086"."PRODUCTS" MODIFY ("CREATE_DATE_TIME" NOT NULL ENABLE);
  ALTER TABLE "FINAL_2232086"."PRODUCTS" MODIFY ("MODIFY_DATE_TIME" NOT NULL ENABLE);
  ALTER TABLE "FINAL_2232086"."PRODUCTS" MODIFY ("PRODUCT_NAME" NOT NULL ENABLE);
  ALTER TABLE "FINAL_2232086"."PRODUCTS" MODIFY ("PRICE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table USER_WEBSITE
--------------------------------------------------------

  ALTER TABLE "FINAL_2232086"."USER_WEBSITE" MODIFY ("CUSTOMER_ID" NOT NULL ENABLE);
  ALTER TABLE "FINAL_2232086"."USER_WEBSITE" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "FINAL_2232086"."USER_WEBSITE" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "FINAL_2232086"."USER_WEBSITE" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "FINAL_2232086"."USER_WEBSITE" ADD CONSTRAINT "USER_WEBSITE_PK" PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "FINAL_2232086"."USER_WEBSITE" ADD CONSTRAINT "USER_WEBSITE_EMAIL_UK" UNIQUE ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "FINAL_2232086"."USER_WEBSITE" MODIFY ("CREATE_DATE_TIME" NOT NULL ENABLE);
  ALTER TABLE "FINAL_2232086"."USER_WEBSITE" MODIFY ("MODIFY_DATE_TIME" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table SALES
--------------------------------------------------------

  ALTER TABLE "FINAL_2232086"."SALES" ADD CONSTRAINT "SALES_CUSTOMER_FK" FOREIGN KEY ("CUSTOMER_ID")
	  REFERENCES "FINAL_2232086"."CUSTOMERS" ("CUSTOMER_ID") ENABLE;
  ALTER TABLE "FINAL_2232086"."SALES" ADD CONSTRAINT "SALES_PRODUCT_FK" FOREIGN KEY ("PRODUCT_ID")
	  REFERENCES "FINAL_2232086"."PRODUCTS" ("PRODUCT_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table USER_WEBSITE
--------------------------------------------------------

  ALTER TABLE "FINAL_2232086"."USER_WEBSITE" ADD CONSTRAINT "USER_WEBSITE_CUSTOMER_IDFK" FOREIGN KEY ("CUSTOMER_ID")
	  REFERENCES "FINAL_2232086"."CUSTOMERS" ("CUSTOMER_ID") ENABLE;
